<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import axios from 'axios'

const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:8000' })
const token = ref(localStorage.getItem('haitoo_token') || '')
const page = ref('dashboard')
const email = ref('operator@haitoo-demo.com')
const password = ref('ChangeMe123!')
const user = ref<any>(null), company = ref<any>(null), shops = ref<any[]>([]), templates = ref<any[]>([]), templateGroups = ref<any[]>([]), tasks = ref<any[]>([]), drafts = ref<any[]>([]), points = ref<any>(null)
const activeShop = ref<number | null>(null), loading = ref(false), error = ref('')
const templateQuery = ref(''), activeGroupId = ref<number | null>(null), selectedTemplateId = ref<number | null>(null)
const showGroupDialog = ref(false), showTemplateDialog = ref(false), newGroupName = ref(''), newTemplateName = ref(''), newTemplateDescription = ref(''), newTemplateGroupId = ref<number | null>(null), newTemplateImage = ref<File | null>(null), newTemplateImagePreview = ref(''), editingTemplate = ref<any>(null)
const creativeAsset = ref<File | null>(null), creativeAssetPreview = ref(''), creativeRequirement = ref(''), creativePlacement = ref<'居中印花' | '满版印花'>('居中印花'), creativeRatio = ref<'1:1' | '3:4'>('1:1'), creativeQuality = ref<'1K' | '2K'>('1K')
const nav = [{key:'dashboard', icon:'◈', label:'工作台'}, {key:'templates', icon:'▦', label:'产品模板'}, {key:'pod', icon:'✦', label:'AI创作'}, {key:'tasks', icon:'◌', label:'任务中心'}, {key:'drafts', icon:'▤', label:'商品草稿'}, {key:'points', icon:'◉', label:'积分中心'}]
const headers = computed(() => ({ Authorization: `Bearer ${token.value}` }))
const pageTitle = computed(() => nav.find(x => x.key === page.value)?.label || '')
const filteredTemplates = computed(() => templates.value.filter(t => (!activeGroupId.value || t.group_id === activeGroupId.value) && t.name.toLowerCase().includes(templateQuery.value.trim().toLowerCase())))
const estimatedCreativePoints = computed(() => creativeQuality.value === '2K' ? 20 : 12)
const selectedTemplate = computed(() => templates.value.find(t => t.id === selectedTemplateId.value))

async function refresh() {
  const h = { headers: headers.value }
  const [me, s, t, g, task, d, p] = await Promise.all([api.get('/me',h), api.get('/shops',h), api.get('/templates',h), api.get('/template-groups',h), api.get('/tasks',h), api.get('/drafts',h), api.get('/points',h)])
  user.value=me.data.user; company.value=me.data.company; shops.value=s.data; templates.value=t.data; templateGroups.value=g.data; tasks.value=task.data; drafts.value=d.data; points.value=p.data
  if (!activeShop.value && shops.value[0]) activeShop.value=shops.value[0].id
  if (!selectedTemplateId.value && templates.value[0]) selectedTemplateId.value=templates.value[0].id
}
async function login() { try { loading.value=true; error.value=''; const {data}=await api.post('/auth/login',{email:email.value,password:password.value}); token.value=data.access_token; localStorage.setItem('haitoo_token',token.value); await refresh() } catch { error.value='登录失败，请检查账号密码' } finally { loading.value=false } }
function onCreativeAssetChange(event: Event) { const file=(event.target as HTMLInputElement).files?.[0] || null; creativeAsset.value=file; creativeAssetPreview.value=file ? URL.createObjectURL(file) : '' }
async function uploadCreativeAsset() { if (!creativeAsset.value) return undefined; const form=new FormData(); form.append('file',creativeAsset.value); const {data}=await api.post('/uploads/creative-asset',form,{headers:headers.value}); return data.url }
async function createTask() { if (!activeShop.value || !selectedTemplateId.value) return; try { const print_url=await uploadCreativeAsset(); await api.post('/tasks',{shop_id:activeShop.value,template_id:selectedTemplateId.value,placement:creativePlacement.value,ratio:creativeRatio.value,quality:creativeQuality.value,print_url,creative_requirement:creativeRequirement.value.trim() || null},{headers:headers.value}); await refresh(); page.value='tasks' } catch (e:any) { error.value=e.response?.data?.detail || '创建 AI 任务失败' } }
async function createGroup() { if (!newGroupName.value.trim()) return; try { await api.post('/template-groups',{name:newGroupName.value.trim()},{headers:headers.value}); newGroupName.value=''; showGroupDialog.value=false; await refresh() } catch (e:any) { error.value=e.response?.data?.detail || '创建分类失败' } }
function openTemplateDialog(template?: any) { editingTemplate.value=template || null; newTemplateName.value=template?.name || ''; newTemplateDescription.value=template?.description || ''; newTemplateGroupId.value=template?.group_id || null; newTemplateImage.value=null; newTemplateImagePreview.value=imageUrl(template?.cover_url); showTemplateDialog.value=true }
function onCoverChange(event: Event) { const file=(event.target as HTMLInputElement).files?.[0] || null; newTemplateImage.value=file; newTemplateImagePreview.value=file ? URL.createObjectURL(file) : imageUrl(editingTemplate.value?.cover_url) }
async function uploadCover() { if (!newTemplateImage.value) return undefined; const form=new FormData(); form.append('file',newTemplateImage.value); const {data}=await api.post('/uploads/template-cover',form,{headers:headers.value}); return data.url }
async function createTemplate() { if (!newTemplateName.value.trim()) return; try { const cover_url=await uploadCover(); const payload={name:newTemplateName.value.trim(),description:newTemplateDescription.value.trim() || null,group_id:newTemplateGroupId.value,cover_url}; if(editingTemplate.value) await api.put(`/templates/${editingTemplate.value.id}`,payload,{headers:headers.value}); else await api.post('/templates',{...payload,color_count:1,sku_count:1,print_areas:[{name:'居中印花'}]},{headers:headers.value}); showTemplateDialog.value=false; await refresh() } catch (e:any) { error.value=e.response?.data?.detail || '保存模板失败' } }
async function deleteTemplate(template:any) { if (!confirm(`确定删除模板「${template.name}」吗？`)) return; try { await api.delete(`/templates/${template.id}`,{headers:headers.value}); if(selectedTemplateId.value===template.id) selectedTemplateId.value=templates.value.find(t=>t.id!==template.id)?.id || null; await refresh() } catch (e:any) { error.value=e.response?.data?.detail || '删除模板失败' } }
function imageUrl(url?: string) { return url ? (url.startsWith('/') ? `${api.defaults.baseURL}${url}` : url) : '' }
function templateCoverUrl(template?: any) { if (template?.cover_url) return imageUrl(template.cover_url); return template?.name === '白色 T恤正面' ? '/template-white-tshirt-front.png' : '/template-tshirt.svg' }
function hasTemplateCover(template?: any) { return Boolean(template?.cover_url || template?.name === '白色 T恤正面') }
function useTemplate(template:any) { selectedTemplateId.value=template.id; page.value='pod' }
async function selectTask(task:any) { await api.post(`/tasks/${task.id}/select`,{result_url:task.result_urls[0]},{headers:headers.value}); await refresh() }
async function makeDraft(task:any) { await api.post(`/tasks/${task.id}/draft`,{}, {headers:headers.value}); await refresh(); page.value='drafts' }
function logout(){ localStorage.removeItem('haitoo_token'); token.value=''; user.value=null }
onMounted(()=>token.value && refresh().catch(logout))
</script>

<template>
  <main v-if="!token" class="login-shell">
    <section class="login-card"><div class="brand-mark">H</div><p class="eyebrow">HAITOO ERP</p><h1>欢迎回到 POD 工作台</h1><p>登录后仅可访问所属公司及已授权店铺。</p><label>邮箱<input v-model="email" type="email" /></label><label>密码<input v-model="password" type="password" /></label><button class="primary full" :disabled="loading" @click="login">{{ loading ? '登录中…' : '登录' }}</button><small>演示账号：operator@haitoo-demo.com / ChangeMe123!</small><p v-if="error" class="error">{{ error }}</p></section>
  </main>
  <main v-else class="app-shell">
    <aside><div class="logo"><span>H</span> HAITOO <b>ERP</b></div><nav><button v-for="item in nav" :key="item.key" :class="{active: page===item.key}" @click="page=item.key"><i>{{item.icon}}</i>{{item.label}}</button></nav><div class="side-help">积分结算<br/><strong>预冻结 · 按实结算</strong></div></aside>
    <section class="content"><header><div><p class="eyebrow">{{ company?.name }}</p><h1>{{ pageTitle }}</h1></div><div class="context"><div class="points-pill"><span>积分余量</span><b>{{points?.available ?? 0}}</b><small>冻结 {{points?.frozen ?? 0}}</small><button @click="page='points'">明细</button></div><select v-model="activeShop"><option v-for="shop in shops" :value="shop.id" :key="shop.id">{{shop.region}} · {{shop.name}}</option></select><span class="member">{{user?.name}} · {{ user?.role === 'company_admin' ? '管理员' : '运营成员' }}</span><button class="ghost" @click="logout">退出</button></div></header>
      <section v-if="page==='dashboard'" class="page"><div class="hero"><div><p>当前店铺 · {{ shops.find(s=>s.id===activeShop)?.name }}</p><h2>今天要先处理什么？</h2><span>从 AI创作到待发布商品，所有进度都在这里。</span></div><button class="primary" @click="page='pod'">✦ 开始 AI创作</button></div><div class="metrics"><article><span>待选图任务</span><b>{{tasks.filter(t=>t.status==='awaiting_selection').length}}</b><em>需要人工确认</em></article><article><span>待发布商品</span><b>{{drafts.length}}</b><em>妙手接口待接入</em></article><article><span>可用积分</span><b>{{points?.available ?? 0}}</b><em>冻结 {{points?.frozen ?? 0}} 积分</em></article></div><div class="two-col"><section class="panel"><h3>待选图任务 <button @click="page='tasks'">查看全部</button></h3><div v-for="task in tasks.slice(0,3)" :key="task.id" class="task-row"><span class="thumb">✦</span><div><strong>AI创作 #{{task.id}}</strong><small>{{task.parameters.placement}} · {{task.parameters.quality}}</small></div><span class="chip blue">{{task.status==='awaiting_selection'?'待选图':'处理中'}}</span></div></section><section class="panel"><h3>快捷操作</h3><button class="quick" @click="page='templates'">▦ 浏览产品模板 <span>→</span></button><button class="quick" @click="page='points'">◉ 查看积分明细 <span>→</span></button></section></div></section>
      <section v-else-if="page==='templates'" class="page"><div class="toolbar"><input v-model="templateQuery" placeholder="搜索模板名称"/><div v-if="user?.role==='company_admin'" class="toolbar-actions"><button class="ghost" @click="showGroupDialog=true">＋ 新增模板分类</button><button class="primary" @click="openTemplateDialog()">＋ 新增模板</button></div></div><div class="template-layout"><section class="groups"><h3>模板分类</h3><button :class="{selected:activeGroupId===null}" @click="activeGroupId=null">全部模板</button><button v-for="group in templateGroups" :key="group.id" :class="{selected:activeGroupId===group.id}" @click="activeGroupId=group.id">{{group.name}}</button></section><section><div class="section-heading"><h2>{{activeGroupId ? templateGroups.find(g=>g.id===activeGroupId)?.name : '全部模板'}}</h2><span>共 {{filteredTemplates.length}} 个模板</span></div><div class="template-grid"><article v-for="t in filteredTemplates" :key="t.id" class="template-card"><div class="template-image" :class="{hasCover: hasTemplateCover(t)}"><img v-if="hasTemplateCover(t)" :src="templateCoverUrl(t)" :alt="t.name"/><span v-else>{{t.name.includes('T恤')?'♧':'♔'}}</span></div><h3>{{t.name}}</h3><p><span class="chip" :class="t.is_platform?'blue':'purple'">{{t.is_platform?'平台模板':'公司私有'}}</span></p><p v-if="t.description" class="template-description">{{t.description}}</p><small>{{t.color_count}} 个颜色 · {{t.sku_count}} 个 SKU</small><div class="template-actions"><button @click="useTemplate(t)">用于 AI创作 →</button><template v-if="!t.is_platform && user?.role==='company_admin'"><button @click="openTemplateDialog(t)">编辑</button><button class="danger" @click="deleteTemplate(t)">删除</button></template></div></article><p v-if="!filteredTemplates.length" class="empty">没有符合条件的模板。</p></div></section></div></section>
      <section v-else-if="page==='pod'" class="page"><div class="mode-tabs"><button>灵感参考</button><button class="active">印花贴合</button><button>创作变体</button></div><section class="pod-panel"><div class="pod-heading"><h2>印花贴合</h2><p>上传印花素材并选择产品模板，生成 AI 创作后的商品效果图。</p></div><div class="pod-grid"><article><label>创作素材</label><label class="upload floral" :class="{hasAsset:creativeAssetPreview}"><input type="file" accept="image/png,image/jpeg,image/webp" @change="onCreativeAssetChange"/><img v-if="creativeAssetPreview" :src="creativeAssetPreview" alt="印花素材预览"/><template v-else><b>✿</b><span>点击上传印花图</span><small>JPG、PNG、WebP，最大 5MB</small></template></label></article><article><label>产品模板</label><select v-model="selectedTemplateId"><option v-for="t in templates" :key="t.id" :value="t.id">{{t.name}}</option></select><div class="product-preview template-preview"><img :src="templateCoverUrl(selectedTemplate)" :alt="selectedTemplate?.name || '产品模板'"/><span>{{selectedTemplate?.name}} · {{creativePlacement}}区</span></div></article><article class="settings"><label class="settings-title">创作参数</label><div class="parameter-fields"><label class="parameter-field"><span>贴合方式</span><select v-model="creativePlacement"><option>居中印花</option><option>满版印花</option></select></label><label class="parameter-field"><span>画面比例</span><select v-model="creativeRatio"><option>1:1</option><option>3:4</option></select></label><label class="parameter-field"><span>清晰度</span><select v-model="creativeQuality"><option>1K</option><option>2K</option></select></label></div><label class="requirement-label">创作要求 <small>（选填）</small><textarea v-model="creativeRequirement" maxlength="1000" placeholder="例如：保留花朵细节，色彩清晰自然，印花完整贴合布料"></textarea></label></article><aside class="estimate"><span>本次印花贴合</span><b>预估冻结 {{estimatedCreativePoints}} 积分</b><small>完成后按实际 AI 用量结算，多退少补。</small><button class="primary full" @click="createTask">✦ 开始印花贴合</button></aside></div></section></section>
      <section v-else-if="page==='tasks'" class="page"><div class="section-heading"><div><h2>任务中心</h2><span>生成结果需要人工选图后才能创建商品草稿。</span></div></div><article v-for="task in tasks" :key="task.id" class="result-card"><div><span class="chip blue">{{task.status}}</span><h3>AI创作 #{{task.id}}</h3><p>预冻结 {{task.estimated_points}} 积分 <span v-if="task.actual_points">· 实际扣除 {{task.actual_points}} 积分</span></p></div><div class="result-images"><button v-for="url in task.result_urls" :key="url" :class="{selected:task.selected_result_url===url}"><img :src="url" alt="生成结果"/></button></div><div><button v-if="task.status==='awaiting_selection'" class="primary" @click="selectTask(task)">确认选图</button><button v-else-if="task.status==='completed'" class="primary" @click="makeDraft(task)">创建商品草稿</button></div></article></section>
      <section v-else-if="page==='drafts'" class="page"><div class="section-heading"><div><h2>商品待发布</h2><span>商品已生成，等待妙手接口创建商品。</span></div><button class="primary">＋ 新建商品草稿</button></div><div class="draft-table"><div class="thead"><span>商品</span><span>SKU/颜色</span><span>来源任务</span><span>状态</span><span>操作</span></div><div v-for="draft in drafts" :key="draft.id" class="trow"><span class="draft-title"><img :src="draft.image_urls[0]"/><b>{{draft.title}}</b></span><span>1 个 SKU · 白色</span><span>#{{draft.source_task_id}}</span><span class="chip orange">待发布至妙手</span><span><button>编辑</button> <button>预览</button></span></div><div v-if="!drafts.length" class="empty">暂无商品草稿，请先在任务中心选图。</div></div></section>
      <section v-else class="page"><div class="points-grid"><article class="balance"><span>可用积分</span><b>{{points?.available ?? 0}}</b><small>公司管理员可管理充值</small></article><article class="balance muted"><span>冻结积分</span><b>{{points?.frozen ?? 0}}</b><small>任务完成后自动结算</small></article><article class="rule"><h3>AI 积分结算规则</h3><p>任务提交时先预冻结，完成后按实际 AI 用量结算，多退少补。</p></article></div><section class="panel ledger"><h3>积分流水</h3><div v-for="row in points?.ledger" :key="row.id" class="ledger-row"><span><b>{{row.entry_type}}</b><small>{{new Date(row.created_at).toLocaleString()}}</small></span><span>{{row.note}}</span><strong :class="row.amount>0?'positive':'negative'">{{row.amount>0?'+':''}}{{row.amount}}</strong><span>余额 {{row.balance_after}}</span></div></section></section>
    </section>
  </main>
  <div v-if="showGroupDialog || showTemplateDialog" class="modal-backdrop" @click.self="showGroupDialog=false; showTemplateDialog=false">
    <section v-if="showGroupDialog" class="modal-card"><h2>新增模板分类</h2><label>分类名称<input v-model="newGroupName" placeholder="例如：夏季服装" @keyup.enter="createGroup" /></label><div class="modal-actions"><button class="ghost" @click="showGroupDialog=false">取消</button><button class="primary" @click="createGroup">确认新增</button></div></section>
    <section v-else class="modal-card template-form"><h2>{{editingTemplate ? '编辑产品模板' : '新增产品模板'}}</h2><p>{{editingTemplate ? '更新模板信息后会立即应用。' : '上传图片并填写描述，创建后可直接用于 AI创作。'}}</p><label>模板名称<input class="template-name-input" v-model="newTemplateName" placeholder="例如：宽松短袖上衣" /></label><label>模板图片<input accept="image/png,image/jpeg,image/webp" type="file" @change="onCoverChange" /><small>{{newTemplateImage ? newTemplateImage.name : editingTemplate?.cover_url ? '保留当前图片' : '支持 JPG、PNG、WebP，最大 5MB'}}</small><div v-if="newTemplateImagePreview" class="template-upload-preview"><img :src="newTemplateImagePreview" alt="模板图片预览" /></div></label><label>模板描述<textarea v-model="newTemplateDescription" maxlength="500" placeholder="描述产品材质、版型和适用的印花区域"></textarea></label><label>模板分类<select v-model="newTemplateGroupId"><option :value="null">未分类</option><option v-for="group in templateGroups" :key="group.id" :value="group.id">{{group.name}}</option></select></label><div class="modal-actions"><button class="ghost" @click="showTemplateDialog=false">取消</button><button class="primary" @click="createTemplate">{{editingTemplate ? '保存修改' : '确认新增'}}</button></div></section>
  </div>
</template>
