"""建立当前数据模型基线

Revision ID: 20260911_01
Revises: 
Create Date: 2026-09-11 10:23:33.572270
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '20260911_01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_provider_settings',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('images_per_task', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('miaoshou_app_id', sa.String(length=255), nullable=True),
    sa.Column('miaoshou_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=24), nullable=True),
    sa.Column('claimed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', name='uq_material_assets_sku')
    )
    op.create_index(op.f('ix_material_assets_company_id'), 'material_assets', ['company_id'], unique=False)
    op.create_index(op.f('ix_material_assets_source_task_id'), 'material_assets', ['source_task_id'], unique=False)
    op.create_index(op.f('ix_material_assets_template_id'), 'material_assets', ['template_id'], unique=False)
    op.create_table('pod_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'AWAITING_SELECTION', 'COMPLETED', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('result_urls', sa.JSON(), nullable=False),
    sa.Column('selected_result_url', sa.String(length=500), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_model', sa.String(length=120), nullable=True),
    sa.Column('provider_task_id', sa.String(length=160), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('result_map', sa.JSON(), nullable=False),
    sa.Column('submit_attempts', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_tasks_company_id'), 'pod_tasks', ['company_id'], unique=False)
    op.create_index('ix_pod_tasks_provider_model', 'pod_tasks', ['provider', 'provider_model'], unique=False)
    op.create_index(op.f('ix_pod_tasks_provider_task_id'), 'pod_tasks', ['provider_task_id'], unique=False)
    op.create_table('product_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('size_chart_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=False),
    sa.Column('sku_items', sa.JSON(), nullable=False),
    sa.Column('miaoshou_collect_box_id', sa.String(length=120), nullable=True),
    sa.Column('tiktok_collect_box_id', sa.String(length=120), nullable=True),
    sa.Column('export_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_drafts_company_id'), 'product_drafts', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_drafts_shop_id'), 'product_drafts', ['shop_id'], unique=False)
    op.create_table('product_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title_template', sa.String(length=500), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('size_chart_url', sa.String(length=500), nullable=True),
    sa.Column('package_weight', sa.Float(), nullable=True),
    sa.Column('package_length', sa.Float(), nullable=True),
    sa.Column('package_width', sa.Float(), nullable=True),
    sa.Column('package_height', sa.Float(), nullable=True),
    sa.Column('sku_specifications', sa.JSON(), nullable=True),
    sa.Column('ai_prompts', sa.JSON(), nullable=True),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('color_count', sa.Integer(), nullable=False),
    sa.Column('sku_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_templates_company_id'), 'product_templates', ['company_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('external_shop_id', sa.String(length=120), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=True),
    sa.Column('auth_status', sa.String(length=30), nullable=False),
    sa.Column('auth_expires_at', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_company_id'), 'shops', ['company_id'], unique=False)
    op.create_table('task_queue_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submit_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('result_interval_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_groups_company_id'), 'template_groups', ['company_id'], unique=False)
    op.create_table('tiktok_category_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('template_version', sa.String(length=40), nullable=True),
    sa.Column('template_blob', sa.LargeBinary().with_variant(mysql.MEDIUMBLOB(), 'mariadb').with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=False),
    sa.Column('parsed_options', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_tiktok_category_catalog_company_name')
    )
    op.create_index('ix_tiktok_category_catalog_company', 'tiktok_category_catalogs', ['company_id'], unique=False)
    op.create_table('user_ai_provider_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_user_ai_provider_credential')
    )
    op.create_index(op.f('ix_user_ai_provider_credentials_company_id'), 'user_ai_provider_credentials', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_ai_provider_credentials_provider'), 'user_ai_provider_credentials', ['provider'], unique=False)
    op.create_index(op.f('ix_user_ai_provider_credentials_user_id'), 'user_ai_provider_credentials', ['user_id'], unique=False)
    op.create_table('user_shops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shop_id', name='uq_user_shop')
    )
    op.create_index(op.f('ix_user_shops_shop_id'), 'user_shops', ['shop_id'], unique=False)
    op.create_index(op.f('ix_user_shops_user_id'), 'user_shops', ['user_id'], unique=False)
    op.create_table('user_template_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', 'name', name='uq_user_template_prompt_name')
    )
    op.create_index(op.f('ix_user_template_prompts_company_id'), 'user_template_prompts', ['company_id'], unique=False)
    op.create_index('ix_user_template_prompts_owner_template', 'user_template_prompts', ['user_id', 'template_id'], unique=False)
    op.create_index(op.f('ix_user_template_prompts_template_id'), 'user_template_prompts', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_template_prompts_user_id'), 'user_template_prompts', ['user_id'], unique=False)
    op.create_table('user_template_white_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', 'name', name='uq_user_template_white_image_name')
    )
    op.create_index(op.f('ix_user_template_white_images_company_id'), 'user_template_white_images', ['company_id'], unique=False)
    op.create_index('ix_user_template_white_images_owner_template', 'user_template_white_images', ['user_id', 'template_id'], unique=False)
    op.create_index(op.f('ix_user_template_white_images_template_id'), 'user_template_white_images', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_template_white_images_user_id'), 'user_template_white_images', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_code', sa.String(length=2), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'COMPANY_ADMIN', 'MEMBER', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'user_code', name='uq_users_company_user_code')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError('基线降级会删除全部业务表，禁止自动执行')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_template_white_images_user_id'), table_name='user_template_white_images')
    op.drop_index(op.f('ix_user_template_white_images_template_id'), table_name='user_template_white_images')
    op.drop_index('ix_user_template_white_images_owner_template', table_name='user_template_white_images')
    op.drop_index(op.f('ix_user_template_white_images_company_id'), table_name='user_template_white_images')
    op.drop_table('user_template_white_images')
    op.drop_index(op.f('ix_user_template_prompts_user_id'), table_name='user_template_prompts')
    op.drop_index(op.f('ix_user_template_prompts_template_id'), table_name='user_template_prompts')
    op.drop_index('ix_user_template_prompts_owner_template', table_name='user_template_prompts')
    op.drop_index(op.f('ix_user_template_prompts_company_id'), table_name='user_template_prompts')
    op.drop_table('user_template_prompts')
    op.drop_index(op.f('ix_user_shops_user_id'), table_name='user_shops')
    op.drop_index(op.f('ix_user_shops_shop_id'), table_name='user_shops')
    op.drop_table('user_shops')
    op.drop_index(op.f('ix_user_ai_provider_credentials_user_id'), table_name='user_ai_provider_credentials')
    op.drop_index(op.f('ix_user_ai_provider_credentials_provider'), table_name='user_ai_provider_credentials')
    op.drop_index(op.f('ix_user_ai_provider_credentials_company_id'), table_name='user_ai_provider_credentials')
    op.drop_table('user_ai_provider_credentials')
    op.drop_index('ix_tiktok_category_catalog_company', table_name='tiktok_category_catalogs')
    op.drop_table('tiktok_category_catalogs')
    op.drop_index(op.f('ix_template_groups_company_id'), table_name='template_groups')
    op.drop_table('template_groups')
    op.drop_table('task_queue_settings')
    op.drop_index(op.f('ix_shops_company_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_product_templates_company_id'), table_name='product_templates')
    op.drop_table('product_templates')
    op.drop_index(op.f('ix_product_drafts_shop_id'), table_name='product_drafts')
    op.drop_index(op.f('ix_product_drafts_company_id'), table_name='product_drafts')
    op.drop_table('product_drafts')
    op.drop_index(op.f('ix_pod_tasks_provider_task_id'), table_name='pod_tasks')
    op.drop_index('ix_pod_tasks_provider_model', table_name='pod_tasks')
    op.drop_index(op.f('ix_pod_tasks_company_id'), table_name='pod_tasks')
    op.drop_table('pod_tasks')
    op.drop_index(op.f('ix_material_assets_template_id'), table_name='material_assets')
    op.drop_index(op.f('ix_material_assets_source_task_id'), table_name='material_assets')
    op.drop_index(op.f('ix_material_assets_company_id'), table_name='material_assets')
    op.drop_table('material_assets')
    op.drop_table('companies')
    op.drop_table('ai_provider_settings')
    # ### end Alembic commands ###
